name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ginasoft
          template: classic
          base: header, repositories, metadata
          config_timezone: America/Argentina/Buenos_Aires

          # Incluir repositorios privados
          repositories_affiliations: owner, collaborator, organization_member
          repositories_private: yes

          # Plugin de lenguajes más usados
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 8

          # Plugin de líneas de código
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_repositories_limit: 4

          # Configuración de repositorios
          repositories: 1000
          repositories_forks: yes
